### ISSUE TITLE
模型训练权重

### ISSUE THREAD

**Issue by ZhuangQingYuan** [lzh-ggs-ddu/SegMind#4]
作者您好，您这篇半监督的工作非常饱满，让我受益匪浅。恳请作者能否将segmind模型以及其余对比模型保存的训练权重发送给我呢，我希望利用该权重进行推理将您的工作复现。我的邮箱是zpatrick7@163.com。期待您的回复。

**Comment by lzh-ggs-ddu** [comment]
不好意思，这个我确实给不了，因为chackpoint文件夹太大，好像有几十个G，毕业后腾电脑空间时已经删除了，估计你得下载代码然后运行才能得到模型权重

**Comment by ZhuangQingYuan** [comment]
好的好的感谢您的回复。打扰您了。我就是想看看能不能拿到最佳的权重的.pth文件的

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月29日 22:10 |
| 收件人 | lzh-ggs-ddu/SegMind ***@***.***> |
| 抄送人 | ZhuangQingYuan ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [lzh-ggs-ddu/SegMind] 模型训练权重 (Issue #4) |

不好意思，这个我确实给不了，因为chackpoint文件夹太大，好像有几十个G，毕业后腾电脑空间时已经删除了，估计你得下载代码然后运行才能得到模型权重
